# Generated by Django 3.2.2 on 2021-05-08 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_actionlog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='action_type',
            field=models.CharField(choices=[('_LOGIN_', 'Login'), ('_REGISTER_', 'Register'), ('_CREATE_POST_', 'Create Post'), ('_GET_', 'Get request'), ('_LIKE_', 'Like'), ('_UNLIKE_', 'Unlike'), ('_REMOVE_LIKE_', 'Remove like of dislike')], max_length=100, null=True),
        ),
    ]
