# Generated by Django 3.2.2 on 2021-05-08 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpostlike',
            options={'ordering': ('-updated_at',), 'verbose_name': 'User post like', 'verbose_name_plural': 'Users posts likes'},
        ),
    ]
